{
 "title": "Main Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running mode (1: Line mode, 0: Battery mode or trouble)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "LP-51",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS_Monitor",
     "select": [
      [
       { "params": [ "lineMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LP-51" }
     ]
    },
    {
     "alias": "E8 1 [servers]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS_Monitor",
     "select": [
      [
       { "params": [ "lineMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "E8_1" }
     ]
    },
    {
     "alias": "E8 2 [VME]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS_Monitor",
     "select": [
      [
       { "params": [ "lineMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "E8_2" }
     ]
    },
    {
     "alias": "E8 3 [HV, LV]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS_Monitor",
     "select": [
      [
       { "params": [ "lineMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "E8_3" }
     ]
    },
    {
     "alias": "E8 5 [corner]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPS_Monitor",
     "select": [
      [
       { "params": [ "lineMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "E8_5" }
     ]
    }
   ]
  },
  { "title": "LaBr alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 4, "x": 16, "y": 0 } },
  { "title": "BGo/CsI alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 } },
  { "title": "Clover 29 HV alert", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 } },
  { "title": "Clover 30 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 } },
  { "title": "Clover 31 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 } },
  { "title": "Clover 32 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 } },
  {
   "title": "Detector Temperature ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Clover 29",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 32",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 34",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 35",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clover 36",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Clover 33 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 } },
  { "title": "Clover 34 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 } },
  { "title": "Clover 35 Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 } },
  { "title": "Clover 36 alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 } },
  {
   "title": "Clover 29 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "29 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 29 I ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "targets": [
    {
     "alias": "ch 1 blue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2 green",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3 red",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4 white",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "E8 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "alias": "E8 Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemValves",
     "select": [
      [
       { "params": [ "temp9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 30 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "30 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
   "targets": [
    {
     "alias": "ch 5 blue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6 red",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7 green",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8 white",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon12|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "30 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 22 },
   "targets": [
    {
     "alias": "ch 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon12|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 31 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "31 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 25 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon6|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon6|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon6|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon6|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "31 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon6|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon6|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon6|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon6|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 32 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "32 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon10|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon10|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon10|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon10|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "32 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon10|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon10|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon10|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon10|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 33 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "Clover 33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "33 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 31 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "33 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 31 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 34 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "Clover 34",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "34 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 34 },
   "targets": [
    {
     "alias": "ch 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon8|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "34 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 34 },
   "targets": [
    {
     "alias": "ch 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon8|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 35 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "35 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 37 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "35 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 37 },
   "targets": [
    {
     "alias": "ch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clover 36 Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "Clover 36",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoolingSystemDet",
     "select": [
      [
       { "params": [ "temp7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "36 HV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 40 },
   "targets": [
    {
     "alias": "ch 5 blue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "VMon13|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "36 I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "alias": "ch 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HVMONDB",
     "select": [
      [
       { "params": [ "IMon13|8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}